import Foundation

enum L10n {
    static func tr(_ key: String, language: AppLanguage) -> String {
        let resolvedLanguage = resolve(language)
        return strings[resolvedLanguage]?[key] ?? strings[.english]?[key] ?? key
    }

    private static func resolve(_ language: AppLanguage) -> AppLanguage {
        if language != .system {
            return language
        }
        let preferred = Locale.preferredLanguages.first?.lowercased() ?? ""
        return preferred.hasPrefix("ru") ? .russian : .english
    }

    private static let strings: [AppLanguage: [String: String]] = [
        .english: [
            "app.name": "FrameScript",
            "welcome.subtitle": "Start with a clean script structure, then shape the visual and editing pass scene by scene.",
            "welcome.newProject": "New Project",
            "welcome.newBlankProject": "New Blank Project",
            "welcome.openProject": "Open Existing Project...",
            "welcome.newFromTemplate": "New From Template",
            "welcome.openDemo": "Open Demo Project",
            "welcome.recent": "Recent",
            "welcome.noRecent": "Saved FrameScript files will appear here after you open or save them.",
            "project.rename": "Rename Project",
            "project.save": "Save",
            "project.saveAs": "Save As...",
            "project.reveal": "Reveal in Finder",
            "project.export": "Export...",
            "project.close": "Close Project",
            "project.browser": "Back to Project Browser",
            "project.unsaved.title": "Save changes before closing?",
            "project.unsaved.message": "This project has changes that are not saved to a FrameScript file.",
            "project.unsaved.untitled": "This untitled project has not been saved yet.",
            "project.unsaved.save": "Save",
            "project.unsaved.discard": "Discard",
            "project.unsaved.cancel": "Cancel",
            "project.untitled": "Untitled Script",
            "dialog.ok": "OK",
            "dialog.delete": "Delete",
            "dialog.openProject.message": "Open a FrameScript project.",
            "dialog.saveProject.message": "Save this project as a FrameScript file.",
            "dialog.exportProject.message": "Export the current project.",
            "dialog.renameProject.message": "Enter a new project name.",
            "dialog.renameScene.message": "Enter a new scene name.",
            "dialog.deleteProject.title": "Delete Project?",
            "dialog.deleteProject.message": "This removes the project from the local library. Saved .framescript files are not deleted.",
            "dialog.deleteScene.title": "Delete Scene?",
            "dialog.deleteScene.message": "This removes the selected scene and its B-roll and editing notes.",
            "dialog.deleteTemplate.title": "Delete Template?",
            "dialog.deleteTemplate.message": "This deletes the custom template. Existing projects are not changed.",
            "dialog.customizeTemplate.title": "Customize built-in template?",
            "dialog.customizeTemplate.message": "FrameScript will save your changes as a user override. You can restore the original later.",
            "dialog.restoreTemplate.title": "Restore original template?",
            "dialog.restoreTemplate.message": "This discards your changes to this built-in template. Custom templates are not affected.",
            "dialog.resetSettings.title": "Reset Settings?",
            "dialog.resetSettings.message": "This returns all app settings to their defaults.",
            "dialog.clearKeys.title": "Clear API Keys?",
            "dialog.clearKeys.message": "This deletes saved AI provider keys from Keychain.",
            "error.openProject": "Could not open project.",
            "error.saveProject": "Could not save project.",
            "error.exportProject": "Could not export project.",
            "error.voicePreview": "Could not play voice preview.",
            "menu.newProject": "New Project",
            "menu.newProjectFromTemplate": "New Project From Template",
            "menu.open": "Open...",
            "menu.openRecent": "Open Recent",
            "menu.noRecentProjects": "No Recent Projects",
            "menu.clearMenu": "Clear Menu",
            "menu.duplicateProject": "Duplicate Project",
            "menu.showProjectBrowser": "Show Project Browser",
            "menu.deleteProject": "Delete Project",
            "menu.import": "Import...",
            "menu.view": "View",
            "menu.scene": "Scene",
            "menu.tools": "Tools",
            "menu.analyzeFullScript": "Analyze Full Script",
            "menu.generateBRoll": "Generate B-Roll For Scene",
            "menu.generateEditing": "Generate Editing Notes For Scene",
            "menu.playVoicePreview": "Play Voice Preview",
            "menu.stopVoicePreview": "Stop Voice Preview",
            "mode.script": "Script",
            "mode.bRoll": "B-Roll",
            "mode.editing": "Editing",
            "scene.add": "Add Scene",
            "scene.kind": "Scene",
            "scene.addAfter": "Add Scene After",
            "scene.rename": "Rename Scene",
            "scene.duplicate": "Duplicate Scene",
            "scene.delete": "Delete Scene",
            "scene.moveUp": "Move Up",
            "scene.moveDown": "Move Down",
            "scene.title": "Scene title",
            "scene.emptyTitle": "No scenes yet",
            "scene.emptyMessage": "Create a scene to start shaping the video.",
            "toolbar.commandPalette": "Command Palette",
            "toolbar.focusMode": "Focus mode",
            "toolbar.settings": "Settings",
            "shortcuts.title": "Shortcuts",
            "command.search": "Type a command or search scenes...",
            "command.switchScript": "Switch to Script",
            "command.switchBRoll": "Switch to B-Roll",
            "command.switchEditing": "Switch to Editing",
            "command.openSettings": "Open Settings",
            "command.toggleFocus": "Toggle Focus",
            "command.toggleSidebar": "Toggle Sidebar",
            "command.toggleAIReview": "Toggle AI Review",
            "command.showShortcuts": "Show Shortcuts",
            "command.closeProject": "Close Project",
            "command.projectBrowser": "Back to Project Browser",
            "settings.general": "General",
            "settings.appearance": "Appearance",
            "settings.editor": "Editor",
            "settings.templates": "Templates",
            "settings.ai": "AI",
            "settings.voice": "Voice",
            "settings.export": "Export",
            "settings.advanced": "Advanced",
            "settings.language": "Language",
            "settings.showBrowserLaunch": "Show project browser on launch",
            "settings.restoreLast": "Restore last project on launch",
            "settings.autosave": "Autosave on change",
            "settings.autosaveInterval": "Autosave interval",
            "settings.defaultTemplate": "Default new project template",
            "settings.blankProjectStart": "Blank project starts with",
            "settings.defaultSplit": "B-roll split by",
            "settings.confirmDelete": "Confirm before deleting scenes/projects",
            "settings.theme": "Theme",
            "settings.accent": "Accent color",
            "settings.sidebarDefault": "Sidebar visible by default",
            "settings.sidebarWidth": "Sidebar width",
            "settings.resetSidebar": "Reset sidebar width",
            "settings.footerShortcuts": "Show footer shortcuts",
            "settings.aiPanel": "Show AI review panel",
            "settings.focusBehavior": "Focus mode hides",
            "settings.wordsPerMinute": "Reading speed estimate",
            "settings.fontSize": "Font size",
            "settings.editorWidth": "Writing column width",
            "settings.lineHeight": "Line height",
            "settings.typewriter": "Typewriter mode",
            "settings.focusParagraph": "Focus paragraph",
            "settings.spellcheck": "Spellcheck",
            "settings.smartQuotes": "Smart quotes",
            "settings.markdownLite": "Markdown-lite",
            "settings.wordCount": "Show word count",
            "settings.sceneDuration": "Show scene duration",
            "settings.defaultNotesVisibility": "Default notes visibility",
            "settings.resetSection": "Reset this section",
            "settings.resetDone": "Reset",
            "theme.system": "System",
            "theme.light": "Light",
            "theme.dark": "Dark",
            "blank.noScenes": "No scenes",
            "blank.oneEmptyScene": "One empty scene",
            "notes.collapsed": "Collapsed",
            "notes.expanded": "Expanded",
            "script.placeholder": "Write the voiceover for this scene...",
            "script.accessibilityLabel": "Scene script",
            "script.notes": "Notes",
            "script.notesPlaceholder": "Optional notes for yourself or the editor...",
            "script.estimated": "estimated",
            "script.words": "words",
            "script.typeMetadata": "Scene type",
            "script.templateSection": "Template section",
            "editor.noScriptText": "This scene has no script text yet.",
            "ai.review": "AI Review",
            "ai.quietTitle": "Quiet until needed",
            "ai.quietMessage": "Run Analyze when you want focused notes on clarity, pacing, hooks, or viewer retention.",
            "ai.analyzeCurrentScene": "Analyze Current Scene",
            "broll.linkedSubtitle": "B-roll linked to script segments",
            "broll.emptyTitle": "No B-roll yet",
            "broll.emptyMessage": "Add a visual idea for this scene or generate a first pass later through AI.",
            "broll.addItem": "Add B-roll Item",
            "broll.addEmpty": "Add B-roll",
            "broll.segmentEmpty": "No B-roll linked to this segment yet.",
            "broll.writeScriptFirst": "Write script text first, then B-roll can be linked to scene / paragraphs / sentences.",
            "broll.item": "B-roll item",
            "broll.duplicateItem": "Duplicate B-roll item",
            "broll.deleteItem": "Delete B-roll item",
            "broll.source": "Source",
            "broll.status": "Status",
            "broll.description": "Description",
            "broll.descriptionPlaceholder": "Describe the shot, action, subject, setting, and visual purpose...",
            "broll.mood": "Mood",
            "broll.moodPlaceholder": "calm, tense, curious...",
            "broll.framing": "Framing",
            "broll.framingPlaceholder": "wide, close-up, screen crop...",
            "broll.motion": "Motion",
            "broll.motionPlaceholder": "static, push-in, pan...",
            "broll.notesPlaceholder": "Source, timing, or production notes...",
            "production.scriptSegment": "Script segment",
            "production.markers": "Production markers",
            "production.unlinked": "Unlinked / scene-level",
            "production.usePreset": "Use preset...",
            "templates.newFromTemplate": "New From Template",
            "templates.manage": "Manage Templates...",
            "templates.createProject": "Create Project",
            "templates.create": "Create Custom Template",
            "templates.duplicate": "Duplicate",
            "templates.delete": "Delete",
            "templates.setDefault": "Set Default",
            "templates.name": "Template",
            "templates.structure": "Structure",
            "templates.sceneName": "Scene name",
            "templates.addScene": "Add Scene",
            "templates.builtIn": "Built-in",
            "templates.customized": "Customized",
            "templates.custom": "Custom",
            "templates.customize": "Customize",
            "templates.restoreOriginal": "Restore original",
            "templates.readOnlyHint": "Customize this built-in template to rename, add, move, or delete scenes.",
            "templates.blankStructure": "Blank template. New projects use the Blank project start setting.",
            "templates.untitled": "Untitled Template",
            "templates.defaultScene": "New scene",
            "templates.copySuffix": "copy",
            "settings.provider": "Provider",
            "settings.model": "Model",
            "settings.baseURL": "Base URL",
            "settings.apiKey": "API key",
            "settings.saveKey": "Save API Key",
            "settings.replaceKey": "Replace Key",
            "settings.deleteKey": "Delete Key",
            "settings.testConnection": "Test AI Connection",
            "settings.inlineCompletion": "Inline completion",
            "settings.completionDelay": "Completion delay",
            "settings.completionLength": "Completion length",
            "settings.reviewMarkers": "Inline AI markers",
            "settings.privacyMode": "Send less context to AI",
            "settings.privacyModeExplanation": "On: AI analysis sends only the current scene title/text where possible. Off: analysis may send full project context for better feedback.",
            "settings.systemVoice": "System voice",
            "settings.default": "Default",
            "settings.speed": "Speed",
            "settings.pitch": "Pitch",
            "settings.usePauses": "Use pauses",
            "settings.exportAudioFormat": "Export audio format",
            "settings.previewVoice": "Preview Voice",
            "settings.stop": "Stop",
            "settings.defaultFormat": "Default format",
            "settings.timestamps": "Include timestamps",
            "settings.sectionNames": "Include scene names",
            "settings.includeBRoll": "Include B-roll",
            "settings.includeEditing": "Include editing notes",
            "settings.includeAI": "Include AI notes",
            "settings.teleprompter": "Teleprompter formatting",
            "settings.exportFolder": "Default export folder",
            "settings.reset": "Reset Settings to Defaults",
            "settings.clearRecents": "Clear Recent Projects",
            "settings.clearKeys": "Clear API Keys",
            "settings.keySaved": "Saved key",
            "settings.keyMissing": "Missing key",
            "settings.keyInvalid": "Invalid key",
            "settings.keyStored": "Key saved",
            "settings.keyNotStored": "No key saved",
            "settings.aiDisabled": "AI disabled",
            "settings.testing": "Testing...",
            "settings.success": "Connection OK",
            "settings.unsupported": "Provider adapter not implemented yet.",
            "settings.failed": "Connection failed",
            "settings.notNeeded": "Not needed while AI is disabled.",
            "newProject.title": "New Project",
            "newProject.blankTitle": "New blank project",
            "newProject.blankDescription": "Creates an empty project using your blank-project start preference.",
            "newProject.name": "Project name",
            "newProject.template": "Template",
            "newProject.create": "Create",
            "export.title": "Export",
            "export.preview": "Preview",
            "export.copy": "Copy to Clipboard",
            "export.saveFile": "Save File...",
            "export.editorHandoff": "Editor handoff",
            "export.label.scene": "Scene",
            "export.label.title": "Title",
            "export.label.duration": "Duration",
            "export.label.estimatedDuration": "Estimated duration",
            "export.label.script": "Script",
            "export.label.broll": "B-roll",
            "export.label.editing": "Editing",
            "export.label.aiNotes": "AI notes",
            "export.label.suggestion": "Suggestion",
            "export.label.source": "Source",
            "export.label.description": "Description",
            "export.label.mood": "Mood",
            "export.label.framing": "Framing",
            "export.label.motion": "Motion",
            "export.label.notes": "Notes",
            "export.label.template": "Template",
            "voiceover.title": "Voiceover",
            "voiceover.message": "Preview the current scene or the full script with the selected macOS voice.",
            "voiceover.playCurrentScene": "Play Current Scene",
            "voiceover.playFullScript": "Play Full Script",
            "voiceover.stop": "Stop",
            "voiceover.exportAudio": "Export Voiceover Audio",
            "voiceover.exportUnavailable": "Audio export is not implemented yet.",
            "voice.empty.title": "Nothing to play.",
            "voice.empty.message": "Add script text before previewing voiceover.",
            "voice.previewText": "FrameScript voice preview.",
            "saveState.saved": "Saved",
            "saveState.edited": "Edited",
            "saveState.saving": "Saving...",
            "help.restoreLast": "Opens the most recently edited project unless the project browser is forced on launch.",
            "help.language": "Sets the language used throughout FrameScript.",
            "help.showBrowserLaunch": "Shows the project browser instead of reopening directly into a project.",
            "help.autosave": "Automatically saves file-backed projects after changes. Untitled projects stay unsaved until Save or Save As.",
            "help.autosaveInterval": "Controls the autosave debounce for saved projects.",
            "help.defaultTemplate": "Chooses the template selected when creating a normal new project.",
            "help.resetTemplates": "Resets only the default template selection to Blank. Customized built-in templates and custom templates are kept.",
            "help.blankProjectStart": "Controls whether the Blank template starts empty or with one scene.",
            "help.defaultSplit": "Controls how script text is divided for B-roll and editing planning.",
            "help.confirmDelete": "Asks before deleting destructive project or scene data.",
            "help.theme": "System follows macOS. Light and Dark force the whole app appearance.",
            "help.accent": "Sets the accent color used for selection and focus states.",
            "help.sidebarDefault": "Controls whether the scene sidebar is visible for new windows.",
            "help.sidebarWidth": "Sets the default scene sidebar width.",
            "help.footerShortcuts": "Shows a compact row of shortcut hints at the bottom of the editor.",
            "help.aiPanel": "Shows the AI review panel beside the writing area.",
            "help.focusBehavior": "Controls which panels are hidden when Focus Mode is active.",
            "help.wordsPerMinute": "Used to estimate the approximate voiceover duration.",
            "help.fontSize": "Sets the editor text size.",
            "help.editorWidth": "Sets the maximum width of the writing column.",
            "help.lineHeight": "Adjusts spacing between editor lines.",
            "help.typewriter": "Keeps the current writing position near the center while typing.",
            "help.focusParagraph": "Softens surrounding paragraphs so the current one is easier to follow.",
            "help.spellcheck": "Uses macOS spell checking in editable text.",
            "help.smartQuotes": "Uses macOS smart punctuation while writing.",
            "help.markdownLite": "Keeps lightweight Markdown conventions available in script text.",
            "help.wordCount": "Shows scene and project word counts.",
            "help.sceneDuration": "Shows estimated read time for each scene.",
            "help.defaultNotesVisibility": "Applies to the current editor until you manually toggle notes, and to newly opened scenes.",
            "help.inlineCompletion": "Allows AI suggestions while writing when a provider is configured.",
            "help.completionDelay": "Wait time before asking AI for an inline suggestion.",
            "help.completionLength": "Controls how much text AI suggests while writing.",
            "help.reviewMarkers": "Shows AI review notes as markers where possible.",
            "help.privacyMode": "On: AI analysis sends only the smallest needed context, usually the current scene or segment. Off: analysis may send broader project context for better suggestions. Rewrite and autocomplete use only the text needed for their request.",
            "help.provider": "Selects which AI adapter should handle completion and review requests.",
            "help.model": "Model name sent to the selected AI provider.",
            "help.baseURL": "Endpoint for OpenAI-compatible APIs.",
            "help.apiKey": "Stored in Keychain and never shown in full.",
            "help.voiceProvider": "Chooses the voice engine used for preview and future audio export.",
            "help.systemVoice": "Selects the macOS voice used by the system provider.",
            "help.voiceSpeed": "Controls voice preview speaking speed.",
            "help.voicePitch": "Controls voice preview pitch.",
            "help.usePauses": "Keeps punctuation pauses in generated speech where supported.",
            "help.exportAudioFormat": "Audio export is not implemented yet, so no audio format is selectable.",
            "help.defaultFormat": "The format preselected when opening the export sheet.",
            "help.timestamps": "Adds estimated scene timing to exported files.",
            "help.sectionNames": "Includes scene titles in exported files.",
            "help.includeBRoll": "Adds B-roll notes where the format supports them.",
            "help.includeEditing": "Adds editing notes where the format supports them.",
            "help.includeAI": "Adds open AI comments to the export.",
            "help.teleprompter": "Formats exported scripts with more breathing room for reading aloud.",
            "help.exportFolder": "Optional default folder to use when exporting projects.",
            "dialog.exportFolder.message": "Choose the default folder for exported script files.",
            "settings.chooseFolder": "Choose...",
            "settings.clearFolder": "Clear",
            "settings.noExportFolder": "No default folder",
            "ai.disabled.type": "AI setup",
            "ai.disabled.message": "Connect an AI provider to run deeper analysis.",
            "ai.disabled.suggestion": "The service layer is provider-neutral; add an adapter without touching the UI.",
            "template.blank": "Blank",
            "template.standardYouTube": "Standard YouTube",
            "template.educational": "Educational",
            "template.storytelling": "Storytelling",
            "template.productReview": "Product Review",
            "template.commentaryEssay": "Commentary / Essay",
            "template.tutorial": "Tutorial",
            "template.scene.hook": "Hook",
            "template.scene.problem": "Problem",
            "template.scene.whyThisMatters": "Why this matters",
            "template.scene.explanation": "Explanation",
            "template.scene.example": "Example",
            "template.scene.takeaway": "Takeaway",
            "template.scene.cta": "CTA",
            "template.scene.context": "Context",
            "template.scene.coreExplanation": "Core explanation",
            "template.scene.summary": "Summary",
            "template.scene.setup": "Setup",
            "template.scene.conflict": "Conflict",
            "template.scene.turningPoint": "Turning point",
            "template.scene.resolution": "Resolution",
            "template.scene.lesson": "Lesson",
            "template.scene.productContext": "Product context",
            "template.scene.whatWorks": "What works",
            "template.scene.whatDoesNot": "What does not",
            "template.scene.verdict": "Verdict",
            "template.scene.thesis": "Thesis",
            "template.scene.argument": "Argument",
            "template.scene.counterpoint": "Counterpoint",
            "template.scene.implication": "Implication",
            "template.scene.closing": "Closing",
            "template.scene.goal": "Goal",
            "template.scene.requirements": "Requirements",
            "template.scene.step1": "Step 1",
            "template.scene.step2": "Step 2",
            "template.scene.commonMistake": "Common mistake",
            "template.scene.recap": "Recap",
            "help.resetSettings": "Restores all application preferences to their defaults.",
            "help.clearRecents": "Removes saved recent project paths from the menu and welcome screen.",
            "help.clearKeys": "Deletes saved AI provider keys from Keychain.",
            "exportFormat.Plain text": "Plain text",
            "exportFormat.Markdown": "Markdown",
            "exportFormat.CSV": "CSV",
            "exportFormat.Production outline": "Production outline",
            "voiceProvider.macOS System Voice": "macOS System Voice",
            "voiceProvider.AI TTS Provider": "AI TTS Provider",
            "aiProvider.Disabled": "Disabled",
            "aiProvider.OpenAI-compatible": "OpenAI-compatible",
            "aiProvider.OpenRouter": "OpenRouter",
            "aiProvider.Anthropic-compatible": "Anthropic-compatible",
            "aiProvider.Gemini": "Gemini",
            "focusMode.Hide panels": "Hide panels",
            "focusMode.Keep sidebar": "Keep sidebar",
            "segmentType.scene": "Scene",
            "segmentType.paragraph": "Paragraph",
            "segmentType.sentence": "Sentence",
            "brollSource.Stock footage": "Stock footage",
            "brollSource.Talking head": "Talking head",
            "brollSource.Screen recording": "Screen recording",
            "brollSource.Animation": "Animation",
            "brollSource.Infographic": "Infographic",
            "brollSource.Text on screen": "Text on screen",
            "brollSource.Meme / insert": "Meme / insert",
            "brollSource.Product shot": "Product shot",
            "brollSource.Screenshot": "Screenshot",
            "brollSource.Custom": "Custom",
            "brollStatus.Idea": "Idea",
            "brollStatus.Planned": "Planned",
            "brollStatus.Sourced": "Sourced",
            "brollStatus.Done": "Done",
            "completionLength.Short": "Short",
            "completionLength.Medium": "Medium",
            "completionLength.Long": "Long",
            "accent.Lavender": "Lavender",
            "accent.Sage": "Sage",
            "accent.Rose": "Rose",
            "accent.Sand": "Sand",
            "accent.Sky": "Sky",
            "accent.Mint": "Mint",
            "accent.Peach": "Peach",
            "accent.Slate": "Slate",
            "generated.startingPoint": "Generated starting point",
            "generated.broll.description": "Add a supporting visual that makes the main idea concrete.",
            "generated.broll.mood": "calm",
            "generated.broll.framing": "clean close-up or screen crop",
            "generated.broll.motion": "subtle push-in",
            "generated.reviewBeforeProduction": "Review and adapt before production.",
            "generated.editing.cleanJumpCuts": "Clean jump cuts",
            "generated.editing.hardCut": "Hard cut",
            "generated.editing.keywordHighlights": "Keyword highlights only",
            "generated.editing.emphasis": "Emphasize the strongest sentence.",
            "generated.editing.zoom": "Use one subtle punch-in.",
            "generated.editing.musicCue": "Keep bed quiet under speech.",
            "generated.editing.graphics": "Use restrained labels only where they clarify.",
            "generated.editing.notes": "Keep the edit quiet and writing-led.",
            "broll.templatePickerTitle": "Choose B-roll template",
            "broll.template.stockFootage": "Stock footage",
            "broll.template.stockFootage.description": "Find a supporting real-world visual for the main idea.",
            "broll.template.stockFootage.mood": "calm",
            "broll.template.stockFootage.framing": "natural close-up",
            "broll.template.stockFootage.motion": "subtle push-in",
            "broll.template.stockFootage.notes": "Keep it specific to the sentence it supports.",
            "broll.template.screenRecording": "Screen recording",
            "broll.template.screenRecording.description": "Record the relevant app, page, or workflow step.",
            "broll.template.screenRecording.mood": "clear",
            "broll.template.screenRecording.framing": "clean screen crop",
            "broll.template.screenRecording.motion": "slow cursor movement",
            "broll.template.screenRecording.notes": "Hide unrelated tabs and private data.",
            "broll.template.talkingHead": "Talking head",
            "broll.template.talkingHead.description": "Use a direct-to-camera beat to clarify the point.",
            "broll.template.talkingHead.mood": "grounded",
            "broll.template.talkingHead.framing": "medium close-up",
            "broll.template.talkingHead.motion": "static",
            "broll.template.talkingHead.notes": "Keep this short so it does not interrupt flow.",
            "broll.template.textOnScreen": "Text on screen",
            "broll.template.textOnScreen.description": "Show a short phrase, term, or contrast from the script.",
            "broll.template.textOnScreen.mood": "clean",
            "broll.template.textOnScreen.framing": "centered text",
            "broll.template.textOnScreen.motion": "simple fade",
            "broll.template.textOnScreen.notes": "Use restrained labels only where they clarify.",
            "broll.template.animation": "Animation",
            "broll.template.animation.description": "Animate the idea with a simple motion graphic.",
            "broll.template.animation.mood": "light",
            "broll.template.animation.framing": "full frame",
            "broll.template.animation.motion": "smooth build",
            "broll.template.animation.notes": "Keep the animation secondary to the voiceover.",
            "broll.template.infographic": "Infographic",
            "broll.template.infographic.description": "Show a small chart, comparison, or labeled structure.",
            "broll.template.infographic.mood": "precise",
            "broll.template.infographic.framing": "wide graphic",
            "broll.template.infographic.motion": "step-by-step reveal",
            "broll.template.infographic.notes": "Limit the amount of text on screen.",
            "broll.template.custom": "Custom",
            "broll.template.custom.description": "",
            "broll.template.custom.mood": "",
            "broll.template.custom.framing": "",
            "broll.template.custom.motion": "",
            "broll.template.custom.notes": "",
            "editing.linkedSubtitle": "Editing notes linked to script segments",
            "editing.emptyTitle": "No editing notes yet",
            "editing.emptyMessage": "Add a minimal edit pass for pacing, captions, music, and on-screen elements.",
            "editing.addItem": "Add Editing Item",
            "editing.addEmpty": "Add editing note",
            "editing.segmentEmpty": "No editing notes linked to this segment yet.",
            "editing.writeScriptFirst": "Write script text first, then editing notes can be linked to scene / paragraphs / sentences.",
            "editing.templatePickerTitle": "Choose editing template",
            "editing.item": "Editing item",
            "editing.duplicateItem": "Duplicate editing item",
            "editing.deleteItem": "Delete editing item",
            "editing.cutStyle": "Cut style",
            "editing.transition": "Transition",
            "editing.subtitles": "Subtitles",
            "editing.subtitlesPlaceholder": "keyword highlights, clean captions...",
            "editing.emphasis": "Emphasis",
            "editing.emphasisPlaceholder": "moment to highlight, thesis to protect...",
            "editing.zoom": "Zoom / motion",
            "editing.zoomPlaceholder": "subtle punch-in, no zoom...",
            "editing.sfx": "SFX",
            "editing.sfxPlaceholder": "soft accent, none...",
            "editing.musicCue": "Music cue",
            "editing.musicCuePlaceholder": "bed starts, fade under...",
            "editing.graphics": "On-screen graphics",
            "editing.graphicsPlaceholder": "Lower thirds, labels, simple motion graphics, charts...",
            "editing.notes": "Editor notes",
            "editing.notesPlaceholder": "Timing, pacing, emphasis, and handoff details...",
            "editing.template.minimal": "Minimal edit",
            "editing.template.minimal.cutStyle": "Clean jump cuts",
            "editing.template.minimal.transition": "Hard cut",
            "editing.template.minimal.subtitleStyle": "Clean captions",
            "editing.template.minimal.emphasis": "",
            "editing.template.minimal.zoom": "Use one subtle punch-in.",
            "editing.template.minimal.sfx": "",
            "editing.template.minimal.musicCue": "Keep bed quiet under speech.",
            "editing.template.minimal.graphics": "",
            "editing.template.minimal.notes": "Keep the edit quiet and writing-led.",
            "editing.template.educational": "Educational YouTube",
            "editing.template.educational.cutStyle": "Clean jump cuts",
            "editing.template.educational.transition": "Hard cut",
            "editing.template.educational.subtitleStyle": "Keyword highlights only",
            "editing.template.educational.emphasis": "Emphasize the strongest sentence.",
            "editing.template.educational.zoom": "Use one subtle punch-in.",
            "editing.template.educational.sfx": "",
            "editing.template.educational.musicCue": "Keep bed quiet under speech.",
            "editing.template.educational.graphics": "Use restrained labels only where they clarify.",
            "editing.template.educational.notes": "Keep the edit quiet and writing-led.",
            "editing.template.storytelling": "Storytelling",
            "editing.template.storytelling.cutStyle": "Let scenes breathe",
            "editing.template.storytelling.transition": "Soft cut",
            "editing.template.storytelling.subtitleStyle": "Minimal captions",
            "editing.template.storytelling.emphasis": "Protect the emotional turn.",
            "editing.template.storytelling.zoom": "Slow push on turning points.",
            "editing.template.storytelling.sfx": "",
            "editing.template.storytelling.musicCue": "Build gently under the story.",
            "editing.template.storytelling.graphics": "Only clarify names, places, or time jumps.",
            "editing.template.storytelling.notes": "Prioritize rhythm over density.",
            "editing.template.fastSocial": "Fast-paced social",
            "editing.template.fastSocial.cutStyle": "Fast punchy cuts",
            "editing.template.fastSocial.transition": "Snap cut",
            "editing.template.fastSocial.subtitleStyle": "Bold keyword captions",
            "editing.template.fastSocial.emphasis": "Hit the strongest claim early.",
            "editing.template.fastSocial.zoom": "Use quick punch-ins sparingly.",
            "editing.template.fastSocial.sfx": "Small accents on beats.",
            "editing.template.fastSocial.musicCue": "Energetic bed under speech.",
            "editing.template.fastSocial.graphics": "Short labels and callouts.",
            "editing.template.fastSocial.notes": "Keep pace high without crowding the script.",
            "editing.template.documentary": "Documentary lite",
            "editing.template.documentary.cutStyle": "Measured cuts",
            "editing.template.documentary.transition": "Natural cut",
            "editing.template.documentary.subtitleStyle": "Clean lower captions",
            "editing.template.documentary.emphasis": "Let evidence carry the point.",
            "editing.template.documentary.zoom": "Slow archive-style movement.",
            "editing.template.documentary.sfx": "",
            "editing.template.documentary.musicCue": "Low bed, fade under key lines.",
            "editing.template.documentary.graphics": "Date, source, and context labels.",
            "editing.template.documentary.notes": "Keep it restrained and credible.",
            "editing.template.custom": "Custom",
            "editing.template.custom.cutStyle": "",
            "editing.template.custom.transition": "",
            "editing.template.custom.subtitleStyle": "",
            "editing.template.custom.emphasis": "",
            "editing.template.custom.zoom": "",
            "editing.template.custom.sfx": "",
            "editing.template.custom.musicCue": "",
            "editing.template.custom.graphics": "",
            "editing.template.custom.notes": ""
        ],
        .russian: [
            "app.name": "FrameScript",
            "welcome.subtitle": "Начните с чистой структуры сценария, затем проработайте визуал и монтаж по сценам.",
            "welcome.newProject": "Новый проект",
            "welcome.newBlankProject": "Новый пустой проект",
            "welcome.openProject": "Открыть проект...",
            "welcome.newFromTemplate": "Новый из шаблона",
            "welcome.openDemo": "Открыть демо-проект",
            "welcome.recent": "Недавние",
            "welcome.noRecent": "Сохраненные файлы FrameScript появятся здесь после открытия или сохранения.",
            "project.rename": "Переименовать проект",
            "project.save": "Сохранить",
            "project.saveAs": "Сохранить как...",
            "project.reveal": "Показать в Finder",
            "project.export": "Экспорт...",
            "project.close": "Закрыть проект",
            "project.browser": "К списку проектов",
            "project.unsaved.title": "Сохранить изменения перед закрытием?",
            "project.unsaved.message": "В проекте есть изменения, не сохраненные в файл FrameScript.",
            "project.unsaved.untitled": "Этот проект еще не был сохранен.",
            "project.unsaved.save": "Сохранить",
            "project.unsaved.discard": "Не сохранять",
            "project.unsaved.cancel": "Отмена",
            "project.untitled": "Новый сценарий",
            "dialog.ok": "OK",
            "dialog.delete": "Удалить",
            "dialog.openProject.message": "Откройте проект FrameScript.",
            "dialog.saveProject.message": "Сохраните проект как файл FrameScript.",
            "dialog.exportProject.message": "Экспорт текущего проекта.",
            "dialog.renameProject.message": "Введите новое название проекта.",
            "dialog.renameScene.message": "Введите новое название сцены.",
            "dialog.deleteProject.title": "Удалить проект?",
            "dialog.deleteProject.message": "Проект будет удален из локальной библиотеки. Сохраненные файлы .framescript не удаляются.",
            "dialog.deleteScene.title": "Удалить сцену?",
            "dialog.deleteScene.message": "Будут удалены выбранная сцена, ее B-roll и заметки монтажа.",
            "dialog.deleteTemplate.title": "Удалить шаблон?",
            "dialog.deleteTemplate.message": "Пользовательский шаблон будет удален. Существующие проекты не изменятся.",
            "dialog.customizeTemplate.title": "Настроить встроенный шаблон?",
            "dialog.customizeTemplate.message": "FrameScript сохранит изменения как пользовательское переопределение. Позже можно восстановить оригинал.",
            "dialog.restoreTemplate.title": "Восстановить исходный шаблон?",
            "dialog.restoreTemplate.message": "Изменения этого встроенного шаблона будут отменены. Пользовательские шаблоны не изменятся.",
            "dialog.resetSettings.title": "Сбросить настройки?",
            "dialog.resetSettings.message": "Все настройки приложения вернутся к значениям по умолчанию.",
            "dialog.clearKeys.title": "Удалить API-ключи?",
            "dialog.clearKeys.message": "Сохраненные ключи ИИ-провайдеров будут удалены из Keychain.",
            "error.openProject": "Не удалось открыть проект.",
            "error.saveProject": "Не удалось сохранить проект.",
            "error.exportProject": "Не удалось экспортировать проект.",
            "error.voicePreview": "Не удалось воспроизвести голос.",
            "menu.newProject": "Новый проект",
            "menu.newProjectFromTemplate": "Новый проект из шаблона",
            "menu.open": "Открыть...",
            "menu.openRecent": "Недавние",
            "menu.noRecentProjects": "Недавних проектов нет",
            "menu.clearMenu": "Очистить меню",
            "menu.duplicateProject": "Дублировать проект",
            "menu.showProjectBrowser": "Показать список проектов",
            "menu.deleteProject": "Удалить проект",
            "menu.import": "Импорт...",
            "menu.view": "Вид",
            "menu.scene": "Сцена",
            "menu.tools": "Инструменты",
            "menu.analyzeFullScript": "Проанализировать весь сценарий",
            "menu.generateBRoll": "Создать B-roll для сцены",
            "menu.generateEditing": "Создать заметки монтажа для сцены",
            "menu.playVoicePreview": "Прослушать голос",
            "menu.stopVoicePreview": "Остановить голос",
            "mode.script": "Сценарий",
            "mode.bRoll": "B-roll",
            "mode.editing": "Монтаж",
            "scene.add": "Добавить сцену",
            "scene.kind": "Сцена",
            "scene.addAfter": "Добавить сцену после",
            "scene.rename": "Переименовать сцену",
            "scene.duplicate": "Дублировать сцену",
            "scene.delete": "Удалить сцену",
            "scene.moveUp": "Выше",
            "scene.moveDown": "Ниже",
            "scene.title": "Название сцены",
            "scene.emptyTitle": "Сцен пока нет",
            "scene.emptyMessage": "Создайте сцену, чтобы начать работу над видео.",
            "toolbar.commandPalette": "Палитра команд",
            "toolbar.focusMode": "Фокус-режим",
            "toolbar.settings": "Настройки",
            "shortcuts.title": "Сочетания клавиш",
            "command.search": "Введите команду или найдите сцену...",
            "command.switchScript": "Перейти к сценарию",
            "command.switchBRoll": "Перейти к B-roll",
            "command.switchEditing": "Перейти к монтажу",
            "command.openSettings": "Открыть настройки",
            "command.toggleFocus": "Фокус-режим",
            "command.toggleSidebar": "Показать/скрыть боковую панель",
            "command.toggleAIReview": "Показать/скрыть анализ ИИ",
            "command.showShortcuts": "Показать сочетания",
            "command.closeProject": "Закрыть проект",
            "command.projectBrowser": "К списку проектов",
            "settings.general": "Основные",
            "settings.appearance": "Внешний вид",
            "settings.editor": "Редактор",
            "settings.templates": "Шаблоны",
            "settings.ai": "ИИ",
            "settings.voice": "Голос",
            "settings.export": "Экспорт",
            "settings.advanced": "Дополнительно",
            "settings.language": "Язык",
            "settings.showBrowserLaunch": "Показывать список проектов при запуске",
            "settings.restoreLast": "Восстанавливать последний проект при запуске",
            "settings.autosave": "Автосохранение при изменениях",
            "settings.autosaveInterval": "Интервал автосохранения",
            "settings.defaultTemplate": "Шаблон нового проекта",
            "settings.blankProjectStart": "Пустой проект начинается с",
            "settings.defaultSplit": "B-roll разбивать по",
            "settings.confirmDelete": "Подтверждать удаление сцен и проектов",
            "settings.theme": "Тема",
            "settings.accent": "Акцентный цвет",
            "settings.sidebarDefault": "Показывать боковую панель при запуске",
            "settings.sidebarWidth": "Ширина боковой панели",
            "settings.resetSidebar": "Сбросить ширину",
            "settings.footerShortcuts": "Показывать сочетания внизу",
            "settings.aiPanel": "Показывать анализ ИИ",
            "settings.focusBehavior": "Фокус-режим скрывает",
            "settings.wordsPerMinute": "Оценка скорости чтения",
            "settings.fontSize": "Размер шрифта",
            "settings.editorWidth": "Ширина колонки текста",
            "settings.lineHeight": "Межстрочный интервал",
            "settings.typewriter": "Режим печатной машинки",
            "settings.focusParagraph": "Фокус на абзаце",
            "settings.spellcheck": "Проверка орфографии",
            "settings.smartQuotes": "Умные кавычки",
            "settings.markdownLite": "Markdown-lite",
            "settings.wordCount": "Показывать количество слов",
            "settings.sceneDuration": "Показывать длительность сцены",
            "settings.defaultNotesVisibility": "Видимость заметок по умолчанию",
            "settings.resetSection": "Сбросить раздел",
            "settings.resetDone": "Сброшено",
            "theme.system": "Системная",
            "theme.light": "Светлая",
            "theme.dark": "Темная",
            "blank.noScenes": "Без сцен",
            "blank.oneEmptyScene": "Одна пустая сцена",
            "notes.collapsed": "Свернуты",
            "notes.expanded": "Развернуты",
            "script.placeholder": "Напишите текст озвучки для этой сцены...",
            "script.accessibilityLabel": "Текст сценария",
            "script.notes": "Заметки",
            "script.notesPlaceholder": "Необязательные заметки для себя или редактора...",
            "script.estimated": "примерно",
            "script.words": "слов",
            "script.typeMetadata": "Тип сцены",
            "script.templateSection": "Раздел шаблона",
            "editor.noScriptText": "В этой сцене пока нет текста сценария.",
            "ai.review": "Анализ ИИ",
            "ai.quietTitle": "Тихо, пока не нужно",
            "ai.quietMessage": "Запустите анализ, когда нужны точные заметки о ясности, темпе, хуке или удержании.",
            "ai.analyzeCurrentScene": "Анализировать текущую сцену",
            "broll.linkedSubtitle": "B-roll, привязанный к фрагментам сценария",
            "broll.emptyTitle": "B-roll пока нет",
            "broll.emptyMessage": "Добавьте визуальную идею для сцены или позже создайте первый вариант через ИИ.",
            "broll.addItem": "Добавить B-roll",
            "broll.addEmpty": "Добавить B-roll",
            "broll.segmentEmpty": "К этому фрагменту пока не привязан B-roll.",
            "broll.writeScriptFirst": "Сначала напишите текст сценария, затем B-roll можно будет привязать к сцене, абзацам или предложениям.",
            "broll.item": "Элемент B-roll",
            "broll.duplicateItem": "Дублировать B-roll",
            "broll.deleteItem": "Удалить B-roll",
            "broll.source": "Источник",
            "broll.status": "Статус",
            "broll.description": "Описание",
            "broll.descriptionPlaceholder": "Опишите кадр, действие, объект, место и визуальную цель...",
            "broll.mood": "Настроение",
            "broll.moodPlaceholder": "спокойное, напряженное, любопытное...",
            "broll.framing": "Кадрирование",
            "broll.framingPlaceholder": "общий план, крупный план, фрагмент экрана...",
            "broll.motion": "Движение",
            "broll.motionPlaceholder": "статично, наезд, панорама...",
            "broll.notesPlaceholder": "Источник, тайминг или производственные заметки...",
            "production.scriptSegment": "Фрагмент сценария",
            "production.markers": "Производственные маркеры",
            "production.unlinked": "Без привязки / на уровне сцены",
            "production.usePreset": "Использовать пресет...",
            "templates.newFromTemplate": "Новый из шаблона",
            "templates.manage": "Управление шаблонами...",
            "templates.createProject": "Создать проект",
            "templates.create": "Создать шаблон",
            "templates.duplicate": "Дублировать",
            "templates.delete": "Удалить",
            "templates.setDefault": "По умолчанию",
            "templates.name": "Шаблон",
            "templates.structure": "Структура",
            "templates.sceneName": "Название сцены",
            "templates.addScene": "Добавить сцену",
            "templates.builtIn": "Встроенный",
            "templates.customized": "Измененный",
            "templates.custom": "Пользовательский",
            "templates.customize": "Настроить",
            "templates.restoreOriginal": "Восстановить оригинал",
            "templates.readOnlyHint": "Настройте встроенный шаблон, чтобы переименовывать, добавлять, перемещать или удалять сцены.",
            "templates.blankStructure": "Пустой шаблон. Новые проекты используют настройку начала пустого проекта.",
            "templates.untitled": "Новый шаблон",
            "templates.defaultScene": "Новая сцена",
            "templates.copySuffix": "копия",
            "settings.provider": "Провайдер",
            "settings.model": "Модель",
            "settings.baseURL": "Base URL",
            "settings.apiKey": "API-ключ",
            "settings.saveKey": "Сохранить ключ",
            "settings.replaceKey": "Заменить ключ",
            "settings.deleteKey": "Удалить ключ",
            "settings.testConnection": "Проверить подключение",
            "settings.inlineCompletion": "Дополнение текста",
            "settings.completionDelay": "Задержка дополнения",
            "settings.completionLength": "Длина дополнения",
            "settings.reviewMarkers": "Встроенные метки ИИ",
            "settings.privacyMode": "Отправлять меньше контекста ИИ",
            "settings.privacyModeExplanation": "Вкл.: анализ ИИ по возможности отправляет только название и текст текущей сцены. Выкл.: анализ может отправлять контекст всего проекта для более точных замечаний.",
            "settings.systemVoice": "Системный голос",
            "settings.default": "По умолчанию",
            "settings.speed": "Скорость",
            "settings.pitch": "Высота",
            "settings.usePauses": "Использовать паузы",
            "settings.exportAudioFormat": "Формат аудиоэкспорта",
            "settings.previewVoice": "Прослушать голос",
            "settings.stop": "Стоп",
            "settings.defaultFormat": "Формат по умолчанию",
            "settings.timestamps": "Добавлять таймкоды",
            "settings.sectionNames": "Добавлять названия сцен",
            "settings.includeBRoll": "Добавлять B-roll",
            "settings.includeEditing": "Добавлять заметки монтажа",
            "settings.includeAI": "Добавлять заметки ИИ",
            "settings.teleprompter": "Формат телесуфлера",
            "settings.exportFolder": "Папка экспорта",
            "settings.reset": "Сбросить настройки",
            "settings.clearRecents": "Очистить недавние проекты",
            "settings.clearKeys": "Удалить API-ключи",
            "settings.keySaved": "Ключ сохранен",
            "settings.keyMissing": "Ключ отсутствует",
            "settings.keyInvalid": "Ключ неверный",
            "settings.keyStored": "Ключ есть",
            "settings.keyNotStored": "Ключ не сохранен",
            "settings.aiDisabled": "ИИ отключен",
            "settings.testing": "Проверка...",
            "settings.success": "Подключение работает",
            "settings.unsupported": "Адаптер провайдера пока не реализован.",
            "settings.failed": "Не удалось подключиться",
            "settings.notNeeded": "Не требуется, пока ИИ отключен.",
            "newProject.title": "Новый проект",
            "newProject.blankTitle": "Новый пустой проект",
            "newProject.blankDescription": "Создает пустой проект с учетом выбранной настройки начала пустого проекта.",
            "newProject.name": "Название проекта",
            "newProject.template": "Шаблон",
            "newProject.create": "Создать",
            "export.title": "Экспорт",
            "export.preview": "Предпросмотр",
            "export.copy": "Скопировать",
            "export.saveFile": "Сохранить файл...",
            "export.editorHandoff": "Передача редактору",
            "export.label.scene": "Сцена",
            "export.label.title": "Название",
            "export.label.duration": "Длительность",
            "export.label.estimatedDuration": "Расчетная длительность",
            "export.label.script": "Сценарий",
            "export.label.broll": "B-roll",
            "export.label.editing": "Монтаж",
            "export.label.aiNotes": "Заметки ИИ",
            "export.label.suggestion": "Предложение",
            "export.label.source": "Источник",
            "export.label.description": "Описание",
            "export.label.mood": "Настроение",
            "export.label.framing": "Кадрирование",
            "export.label.motion": "Движение",
            "export.label.notes": "Заметки",
            "export.label.template": "Шаблон",
            "voiceover.title": "Озвучка",
            "voiceover.message": "Прослушайте текущую сцену или весь сценарий выбранным системным голосом macOS.",
            "voiceover.playCurrentScene": "Воспроизвести текущую сцену",
            "voiceover.playFullScript": "Воспроизвести весь сценарий",
            "voiceover.stop": "Остановить",
            "voiceover.exportAudio": "Экспорт аудио озвучки",
            "voiceover.exportUnavailable": "Экспорт озвучки пока не реализован.",
            "voice.empty.title": "Нечего воспроизводить.",
            "voice.empty.message": "Добавьте текст сценария перед прослушиванием озвучки.",
            "voice.previewText": "Предпросмотр голоса FrameScript.",
            "saveState.saved": "Сохранено",
            "saveState.edited": "Изменено",
            "saveState.saving": "Сохранение...",
            "help.restoreLast": "Открывает последний отредактированный проект, если список проектов не включен принудительно.",
            "help.language": "Задает язык интерфейса FrameScript.",
            "help.showBrowserLaunch": "Показывает список проектов вместо прямого открытия проекта.",
            "help.autosave": "Автоматически сохраняет изменения в проектах, уже сохраненных в файл. Новые проекты остаются несохраненными до команды Сохранить или Сохранить как.",
            "help.autosaveInterval": "Задает задержку автосохранения для сохраненных проектов.",
            "help.defaultTemplate": "Выбирает шаблон для обычного нового проекта.",
            "help.resetTemplates": "Сбрасывает только выбор шаблона по умолчанию на пустой. Измененные встроенные и пользовательские шаблоны сохраняются.",
            "help.blankProjectStart": "Определяет, будет ли пустой шаблон без сцен или с одной сценой.",
            "help.defaultSplit": "Определяет, как делить текст сценария для планирования B-roll и монтажа.",
            "help.confirmDelete": "Спрашивает подтверждение перед удалением проекта или сцены.",
            "help.theme": "Системная следует macOS. Светлая и темная принудительно меняют весь интерфейс.",
            "help.accent": "Задает акцентный цвет выбора и фокуса.",
            "help.sidebarDefault": "Определяет, видна ли боковая панель в новых окнах.",
            "help.sidebarWidth": "Задает стандартную ширину боковой панели сцен.",
            "help.footerShortcuts": "Показывает компактные подсказки клавиш внизу редактора.",
            "help.aiPanel": "Показывает панель анализа ИИ рядом с текстом.",
            "help.focusBehavior": "Определяет, какие панели скрываются в фокус-режиме.",
            "help.wordsPerMinute": "Используется для примерной оценки длительности озвучки.",
            "help.fontSize": "Задает размер текста редактора.",
            "help.editorWidth": "Задает максимальную ширину колонки редактора.",
            "help.lineHeight": "Настраивает расстояние между строками редактора.",
            "help.typewriter": "Удерживает текущую строку ближе к центру во время набора.",
            "help.focusParagraph": "Приглушает соседние абзацы, чтобы текущий было проще читать.",
            "help.spellcheck": "Использует проверку орфографии macOS в полях текста.",
            "help.smartQuotes": "Использует умную пунктуацию macOS при письме.",
            "help.markdownLite": "Оставляет легкие Markdown-правила в тексте сценария.",
            "help.wordCount": "Показывает количество слов в сцене и проекте.",
            "help.sceneDuration": "Показывает расчетное время чтения сцены.",
            "help.defaultNotesVisibility": "Действует в текущем редакторе, пока вы не переключите заметки вручную, и для новых открытых сцен.",
            "help.inlineCompletion": "Позволяет ИИ предлагать продолжение текста при настроенном провайдере.",
            "help.completionDelay": "Пауза перед запросом подсказки ИИ.",
            "help.completionLength": "Определяет, сколько текста предлагает ИИ.",
            "help.reviewMarkers": "Показывает заметки анализа ИИ как маркеры там, где это возможно.",
            "help.privacyMode": "Вкл.: анализ ИИ отправляет только минимально необходимый контекст, обычно текущую сцену или фрагмент. Выкл.: для более точных предложений анализ может отправлять более широкий контекст проекта. Перезапись и автодополнение используют только текст, необходимый для запроса.",
            "help.provider": "Выбирает адаптер ИИ для дополнений и анализа.",
            "help.model": "Название модели, отправляемое выбранному ИИ-провайдеру.",
            "help.baseURL": "Адрес OpenAI-совместимого API.",
            "help.apiKey": "Хранится в Keychain и никогда не показывается полностью.",
            "help.voiceProvider": "Выбирает движок голоса для предпросмотра и будущего аудиоэкспорта.",
            "help.systemVoice": "Выбирает голос macOS для системного провайдера.",
            "help.voiceSpeed": "Настраивает скорость предпросмотра голоса.",
            "help.voicePitch": "Настраивает высоту голоса.",
            "help.usePauses": "Сохраняет паузы пунктуации в речи, если провайдер поддерживает.",
            "help.exportAudioFormat": "Экспорт озвучки пока не реализован, поэтому формат аудио не выбирается.",
            "help.defaultFormat": "Формат, выбранный при открытии окна экспорта.",
            "help.timestamps": "Добавляет расчетное время сцен в экспорт.",
            "help.sectionNames": "Добавляет названия сцен в экспорт.",
            "help.includeBRoll": "Добавляет заметки B-roll там, где формат это поддерживает.",
            "help.includeEditing": "Добавляет заметки монтажа там, где формат это поддерживает.",
            "help.includeAI": "Добавляет открытые комментарии ИИ в экспорт.",
            "help.teleprompter": "Добавляет больше воздуха в экспортированный текст для чтения вслух.",
            "help.exportFolder": "Необязательная папка по умолчанию для экспорта проектов.",
            "dialog.exportFolder.message": "Выберите папку по умолчанию для экспорта сценариев.",
            "settings.chooseFolder": "Выбрать...",
            "settings.clearFolder": "Очистить",
            "settings.noExportFolder": "Папка не выбрана",
            "ai.disabled.type": "Настройка ИИ",
            "ai.disabled.message": "Подключите ИИ-провайдера, чтобы запускать более глубокий анализ.",
            "ai.disabled.suggestion": "Сервисный слой не зависит от провайдера; адаптер можно добавить без изменений UI.",
            "template.blank": "Пустой",
            "template.standardYouTube": "Стандартный YouTube",
            "template.educational": "Образовательный",
            "template.storytelling": "Сторителлинг",
            "template.productReview": "Обзор продукта",
            "template.commentaryEssay": "Комментарий / эссе",
            "template.tutorial": "Инструкция",
            "template.scene.hook": "Хук",
            "template.scene.problem": "Проблема",
            "template.scene.whyThisMatters": "Почему это важно",
            "template.scene.explanation": "Объяснение",
            "template.scene.example": "Пример",
            "template.scene.takeaway": "Вывод",
            "template.scene.cta": "Призыв к действию",
            "template.scene.context": "Контекст",
            "template.scene.coreExplanation": "Основное объяснение",
            "template.scene.summary": "Итоги",
            "template.scene.setup": "Завязка",
            "template.scene.conflict": "Конфликт",
            "template.scene.turningPoint": "Поворотный момент",
            "template.scene.resolution": "Развязка",
            "template.scene.lesson": "Урок",
            "template.scene.productContext": "Контекст продукта",
            "template.scene.whatWorks": "Что работает",
            "template.scene.whatDoesNot": "Что не работает",
            "template.scene.verdict": "Вердикт",
            "template.scene.thesis": "Тезис",
            "template.scene.argument": "Аргумент",
            "template.scene.counterpoint": "Контраргумент",
            "template.scene.implication": "Следствие",
            "template.scene.closing": "Завершение",
            "template.scene.goal": "Цель",
            "template.scene.requirements": "Требования",
            "template.scene.step1": "Шаг 1",
            "template.scene.step2": "Шаг 2",
            "template.scene.commonMistake": "Частая ошибка",
            "template.scene.recap": "Краткий повтор",
            "help.resetSettings": "Возвращает все настройки приложения к значениям по умолчанию.",
            "help.clearRecents": "Удаляет пути недавних проектов из меню и экрана приветствия.",
            "help.clearKeys": "Удаляет сохраненные ключи ИИ-провайдеров из Keychain.",
            "exportFormat.Plain text": "Обычный текст",
            "exportFormat.Markdown": "Markdown",
            "exportFormat.CSV": "CSV",
            "exportFormat.Production outline": "Производственный план",
            "voiceProvider.macOS System Voice": "Системный голос macOS",
            "voiceProvider.AI TTS Provider": "ИИ-провайдер TTS",
            "aiProvider.Disabled": "Отключено",
            "aiProvider.OpenAI-compatible": "OpenAI-совместимый",
            "aiProvider.OpenRouter": "OpenRouter",
            "aiProvider.Anthropic-compatible": "Anthropic-совместимый",
            "aiProvider.Gemini": "Gemini",
            "focusMode.Hide panels": "Скрывать панели",
            "focusMode.Keep sidebar": "Оставлять боковую панель",
            "segmentType.scene": "Сцена",
            "segmentType.paragraph": "Абзац",
            "segmentType.sentence": "Предложение",
            "brollSource.Stock footage": "Стоковое видео",
            "brollSource.Talking head": "Говорящая голова",
            "brollSource.Screen recording": "Запись экрана",
            "brollSource.Animation": "Анимация",
            "brollSource.Infographic": "Инфографика",
            "brollSource.Text on screen": "Текст на экране",
            "brollSource.Meme / insert": "Мем / вставка",
            "brollSource.Product shot": "Кадр продукта",
            "brollSource.Screenshot": "Скриншот",
            "brollSource.Custom": "Другое",
            "brollStatus.Idea": "Идея",
            "brollStatus.Planned": "Запланировано",
            "brollStatus.Sourced": "Найдено",
            "brollStatus.Done": "Готово",
            "completionLength.Short": "Короткая",
            "completionLength.Medium": "Средняя",
            "completionLength.Long": "Длинная",
            "accent.Lavender": "Лавандовый",
            "accent.Sage": "Шалфей",
            "accent.Rose": "Розовый",
            "accent.Sand": "Песочный",
            "accent.Sky": "Небесный",
            "accent.Mint": "Мятный",
            "accent.Peach": "Персиковый",
            "accent.Slate": "Сланцевый",
            "generated.startingPoint": "Созданная отправная точка",
            "generated.broll.description": "Добавьте поддерживающий визуал, который делает главную идею конкретной.",
            "generated.broll.mood": "спокойное",
            "generated.broll.framing": "чистый крупный план или фрагмент экрана",
            "generated.broll.motion": "легкий наезд",
            "generated.reviewBeforeProduction": "Проверьте и адаптируйте перед производством.",
            "generated.editing.cleanJumpCuts": "Чистые склейки",
            "generated.editing.hardCut": "Жесткая склейка",
            "generated.editing.keywordHighlights": "Только выделение ключевых слов",
            "generated.editing.emphasis": "Подчеркните самое сильное предложение.",
            "generated.editing.zoom": "Используйте один легкий наезд.",
            "generated.editing.musicCue": "Держите фон тихим под речью.",
            "generated.editing.graphics": "Используйте сдержанные подписи только там, где они проясняют.",
            "generated.editing.notes": "Сохраните спокойный монтаж с фокусом на тексте.",
            "broll.templatePickerTitle": "Выберите шаблон B-roll",
            "broll.template.stockFootage": "Стоковое видео",
            "broll.template.stockFootage.description": "Найдите поддерживающий реальный визуал для главной идеи.",
            "broll.template.stockFootage.mood": "спокойное",
            "broll.template.stockFootage.framing": "естественный крупный план",
            "broll.template.stockFootage.motion": "легкий наезд",
            "broll.template.stockFootage.notes": "Привяжите визуал к конкретной фразе.",
            "broll.template.screenRecording": "Запись экрана",
            "broll.template.screenRecording.description": "Запишите нужное приложение, страницу или шаг процесса.",
            "broll.template.screenRecording.mood": "ясное",
            "broll.template.screenRecording.framing": "чистый фрагмент экрана",
            "broll.template.screenRecording.motion": "медленное движение курсора",
            "broll.template.screenRecording.notes": "Скройте лишние вкладки и приватные данные.",
            "broll.template.talkingHead": "Говорящая голова",
            "broll.template.talkingHead.description": "Добавьте короткий фрагмент в камеру для пояснения.",
            "broll.template.talkingHead.mood": "уверенное",
            "broll.template.talkingHead.framing": "средний крупный план",
            "broll.template.talkingHead.motion": "статично",
            "broll.template.talkingHead.notes": "Сделайте фрагмент коротким, чтобы не сбивать темп.",
            "broll.template.textOnScreen": "Текст на экране",
            "broll.template.textOnScreen.description": "Покажите короткую фразу, термин или контраст из сценария.",
            "broll.template.textOnScreen.mood": "чистое",
            "broll.template.textOnScreen.framing": "текст по центру",
            "broll.template.textOnScreen.motion": "простое появление",
            "broll.template.textOnScreen.notes": "Используйте подписи только для ясности.",
            "broll.template.animation": "Анимация",
            "broll.template.animation.description": "Объясните идею простой motion-графикой.",
            "broll.template.animation.mood": "легкое",
            "broll.template.animation.framing": "полный кадр",
            "broll.template.animation.motion": "плавная сборка",
            "broll.template.animation.notes": "Анимация должна поддерживать озвучку, а не спорить с ней.",
            "broll.template.infographic": "Инфографика",
            "broll.template.infographic.description": "Покажите небольшой график, сравнение или схему.",
            "broll.template.infographic.mood": "точное",
            "broll.template.infographic.framing": "широкая графика",
            "broll.template.infographic.motion": "пошаговое раскрытие",
            "broll.template.infographic.notes": "Ограничьте количество текста на экране.",
            "broll.template.custom": "Другое",
            "broll.template.custom.description": "",
            "broll.template.custom.mood": "",
            "broll.template.custom.framing": "",
            "broll.template.custom.motion": "",
            "broll.template.custom.notes": "",
            "editing.linkedSubtitle": "Монтажные заметки, привязанные к фрагментам сценария",
            "editing.emptyTitle": "Заметок монтажа пока нет",
            "editing.emptyMessage": "Добавьте базовый монтажный проход для темпа, субтитров, музыки и экранных элементов.",
            "editing.addItem": "Добавить монтаж",
            "editing.addEmpty": "Добавить заметку монтажа",
            "editing.segmentEmpty": "К этому фрагменту пока не привязаны монтажные заметки.",
            "editing.writeScriptFirst": "Сначала напишите текст сценария, затем монтажные заметки можно будет привязать к сцене, абзацам или предложениям.",
            "editing.templatePickerTitle": "Выберите шаблон монтажа",
            "editing.item": "Элемент монтажа",
            "editing.duplicateItem": "Дублировать элемент монтажа",
            "editing.deleteItem": "Удалить элемент монтажа",
            "editing.cutStyle": "Стиль склеек",
            "editing.transition": "Переход",
            "editing.subtitles": "Субтитры",
            "editing.subtitlesPlaceholder": "выделение ключевых слов, чистые подписи...",
            "editing.emphasis": "Акцент",
            "editing.emphasisPlaceholder": "что подчеркнуть, какой тезис сохранить...",
            "editing.zoom": "Зум / движение",
            "editing.zoomPlaceholder": "легкий наезд, без зума...",
            "editing.sfx": "SFX",
            "editing.sfxPlaceholder": "мягкий акцент, без эффектов...",
            "editing.musicCue": "Музыка",
            "editing.musicCuePlaceholder": "фон начинается, затухает под речь...",
            "editing.graphics": "Графика на экране",
            "editing.graphicsPlaceholder": "Нижние титры, подписи, простая motion-графика, графики...",
            "editing.notes": "Заметки редактору",
            "editing.notesPlaceholder": "Тайминг, темп, акценты и детали передачи...",
            "editing.template.minimal": "Минимальный монтаж",
            "editing.template.minimal.cutStyle": "Чистые склейки",
            "editing.template.minimal.transition": "Жесткая склейка",
            "editing.template.minimal.subtitleStyle": "Чистые субтитры",
            "editing.template.minimal.emphasis": "",
            "editing.template.minimal.zoom": "Используйте один легкий наезд.",
            "editing.template.minimal.sfx": "",
            "editing.template.minimal.musicCue": "Держите фон тихим под речью.",
            "editing.template.minimal.graphics": "",
            "editing.template.minimal.notes": "Сохраните спокойный монтаж с фокусом на тексте.",
            "editing.template.educational": "Образовательный YouTube",
            "editing.template.educational.cutStyle": "Чистые склейки",
            "editing.template.educational.transition": "Жесткая склейка",
            "editing.template.educational.subtitleStyle": "Только выделение ключевых слов",
            "editing.template.educational.emphasis": "Подчеркните самое сильное предложение.",
            "editing.template.educational.zoom": "Используйте один легкий наезд.",
            "editing.template.educational.sfx": "",
            "editing.template.educational.musicCue": "Держите фон тихим под речью.",
            "editing.template.educational.graphics": "Используйте сдержанные подписи только там, где они проясняют.",
            "editing.template.educational.notes": "Сохраните спокойный монтаж с фокусом на тексте.",
            "editing.template.storytelling": "Сторителлинг",
            "editing.template.storytelling.cutStyle": "Дайте сценам дышать",
            "editing.template.storytelling.transition": "Мягкая склейка",
            "editing.template.storytelling.subtitleStyle": "Минимальные субтитры",
            "editing.template.storytelling.emphasis": "Сохраните эмоциональный поворот.",
            "editing.template.storytelling.zoom": "Медленный наезд на поворотных моментах.",
            "editing.template.storytelling.sfx": "",
            "editing.template.storytelling.musicCue": "Мягко наращивайте фон под историю.",
            "editing.template.storytelling.graphics": "Только имена, места или скачки времени.",
            "editing.template.storytelling.notes": "Приоритет ритму, а не плотности.",
            "editing.template.fastSocial": "Быстрый соцформат",
            "editing.template.fastSocial.cutStyle": "Быстрые энергичные склейки",
            "editing.template.fastSocial.transition": "Резкая склейка",
            "editing.template.fastSocial.subtitleStyle": "Жирные ключевые подписи",
            "editing.template.fastSocial.emphasis": "Дайте сильнейший тезис рано.",
            "editing.template.fastSocial.zoom": "Используйте быстрые наезды умеренно.",
            "editing.template.fastSocial.sfx": "Небольшие акценты по битам.",
            "editing.template.fastSocial.musicCue": "Энергичный фон под речь.",
            "editing.template.fastSocial.graphics": "Короткие подписи и выноски.",
            "editing.template.fastSocial.notes": "Держите высокий темп без перегруза.",
            "editing.template.documentary": "Легкая документалистика",
            "editing.template.documentary.cutStyle": "Размеренные склейки",
            "editing.template.documentary.transition": "Естественная склейка",
            "editing.template.documentary.subtitleStyle": "Чистые нижние подписи",
            "editing.template.documentary.emphasis": "Пусть доказательства несут тезис.",
            "editing.template.documentary.zoom": "Медленное архивное движение.",
            "editing.template.documentary.sfx": "",
            "editing.template.documentary.musicCue": "Низкий фон, тише под ключевыми строками.",
            "editing.template.documentary.graphics": "Дата, источник и контекст.",
            "editing.template.documentary.notes": "Сдержанно и убедительно.",
            "editing.template.custom": "Другое",
            "editing.template.custom.cutStyle": "",
            "editing.template.custom.transition": "",
            "editing.template.custom.subtitleStyle": "",
            "editing.template.custom.emphasis": "",
            "editing.template.custom.zoom": "",
            "editing.template.custom.sfx": "",
            "editing.template.custom.musicCue": "",
            "editing.template.custom.graphics": "",
            "editing.template.custom.notes": ""
        ]
    ]
}

@MainActor
extension AppState {
    func displayName(_ value: AppearanceTheme) -> String {
        switch value {
        case .system: localized("theme.system")
        case .light: localized("theme.light")
        case .dark: localized("theme.dark")
        }
    }

    func displayName(_ value: AccentPalette) -> String {
        localized("accent.\(value.rawValue)")
    }

    func displayName(_ value: ExportFormat) -> String {
        localized("exportFormat.\(value.rawValue)")
    }

    func displayName(_ value: VoiceProviderKind) -> String {
        localized("voiceProvider.\(value.rawValue)")
    }

    func displayName(_ value: AIProviderKind) -> String {
        localized("aiProvider.\(value.rawValue)")
    }

    func displayName(_ value: FocusModeBehavior) -> String {
        localized("focusMode.\(value.rawValue)")
    }

    func displayName(_ value: SegmentType) -> String {
        localized("segmentType.\(value.rawValue)")
    }

    func displayName(_ value: SectionType) -> String {
        switch value {
        case .hook: localized("template.scene.hook")
        case .problem: localized("template.scene.problem")
        case .whyThisMatters: localized("template.scene.whyThisMatters")
        case .explanation: localized("template.scene.explanation")
        case .example: localized("template.scene.example")
        case .takeaway: localized("template.scene.takeaway")
        case .cta: localized("template.scene.cta")
        case .custom: localized("script.typeMetadata")
        }
    }

    func displayName(_ value: BRollSourceType) -> String {
        localized("brollSource.\(value.rawValue)")
    }

    func displayName(_ value: BRollStatus) -> String {
        localized("brollStatus.\(value.rawValue)")
    }

    func displayName(_ value: CompletionLength) -> String {
        localized("completionLength.\(value.rawValue)")
    }

    func displayName(_ value: SaveState) -> String {
        switch value {
        case .saved: localized("saveState.saved")
        case .edited: localized("saveState.edited")
        case .autosaving: localized("saveState.saving")
        }
    }
}
